import classnames from 'classnames'
import './globals.css'
import { Inter } from 'next/font/google'
import { ErrorProvider } from '@/components/wrappers/ErrorProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const classes = classnames(inter.className,
    'bg-dark text-white w-full	'
  )
  return (
    <html lang="en">
      <body className={classes}>
        <ErrorProvider>
          {children}
        </ErrorProvider>
      </body>
    </html>
  )
}
